- hosts: 192.1.1.224
  become: true
  become_method: sudo
  tasks:
  - name: fetch file
    fetch: 
      src: /var/lib/rabbitmq/.erlang.cookie
      dest: temp/

- hosts: 192.1.1.47
  become: true
  become_method: sudo
  tasks:
  - name: copy file
    copy:
      src: /home/smartlis/.erlang.cookie
      dest: /var/lib/rabbitmq
      force: yes
