- name: install rabbitmq
  hosts: slrabbit
  become: yes
  become_user: root
  remote_user: smartlis
  vars_files:
    - roles/erlang-slrabbitmq/vars/erlang_slrabbitmq.yml
  
  roles:
    - erlang-slrabbitmq
    - slrabbit
