- hosts: Ansible
  become: yes
  vars_files:
    - vars/vmware_vms.yml
  
  tasks:
  - name: Update /etc/hosts from inventory
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      state: present
    loop: "{{ vmware_smartlis_deployment.keys() }} {{ item.value.networks[0].ip }}"
