- hosts: localhost
  become: yes
  vars_files:
    - vars/vmware_vms.yml
  
  tasks:
- name: Update /etc/hosts from inventory
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item }}
    state: present
  with_items: "{{ vmware_smartlis_deployment.keys() }}"
