- hosts: "{{ servers }}"

  tasks:
  - name: Check CPU load average
    win_command: powershell.exe "Get-WmiObject win32_processor | Measure-Object -property LoadPercentage -Average | Select Average | Format-List"
    register: cpu_average
    
  - name: debug
    debug:
      msg: "{{ cpu_average.stdout_lines[2].split()[2] }}"
  
  - name: Set CPU load average fact
    set_fact:
      cpu_load: "{{ cpu_average.stdout_lines[2].split()[2] }}"
      
  - name: Send slack message when CPU load is over 90%
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ ansible_hostname }} overall CPU load is {{ cpu_load }}% and top 3 CPU consumers are:"
    when: (cpu_load > 90)
    delegate_to: localhost
  
  - name: Check top 5 CPU load process
    win_command: powershell.exe $cpucores = (Get-WMIObject Win32_ComputerSystem).NumberOfLogicalProcessors; (Get-Counter '\Proceso(*)\% de tiempo de procesador').CounterSamples | Select InstanceName, @{Name='CPU';Expression={[Decimal]::Round(($_.CookedValue / $cpucores), 2)}} | sort *CPU* -Descending | select -First 5 | ConvertTo-Json
    register: cpu_usage
 
  - name: Set Output CPU usage fact by process
    set_fact:
      sys_cpu: "{{ cpu_usage.stdout | from_json }}"
      
  - name: debug
    debug:
      msg: "{{ sys_cpu }}"
      
  - name: Send slack message when CPU load is over 90%
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ item.InstanceName }} -> {{ item.CPU }}%"
    loop: "{{ sys_cpu | list }}"
    when: (item.InstanceName != '_total') and (item.InstanceName != 'idle')
    delegate_to: localhost
    
    
