- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: superv_status
    
  - name:
    set_fact:
      supervisor_proc: "{{ superv_status.stdout_lines }}"
    shell: supervisorctl stop "{{ item }}"
    with_items:
      - "{{ supervisor_proc }}"
