- hosts: "{{ servers }}"
    
  tasks:
  - name: check supervisor programs running
    become: yes
    shell: supervisorctl {{ item }}
    with_items:
      - status
    register: supervisor_status
    
  - name: debug
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ supervisor_status.results.stdout_lines.find("RUNNING") }}"
