- hosts: localhost
  
  tasks:
  - name: Get elastic cluster info
    uri:
      url: http://10.233.16.105:9200/_cluster/health
      return_content: yes
    register: cluster_health
    
  - name: Send message when elastic cluster health is not green
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: Elasticsearch cluster "{{ item.cluster_name }} status is {{ item.status }}, maybe one node is down"
    loop: 
      - "{{ cluster_health.json }}"
    when: item.status != 'green'
    delegate_to: localhost
    
  - name: Send message when elastic cluster is relocating shards
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: Elasticsearch cluster "{{ item.cluster_name }} is relocating shards, shards being relocated={{ item.relocating_shards }}. Maybe one node is down"
    loop: 
      - "{{ cluster_health.json }}"
    when: item.relocating_shards > 0
    delegate_to: localhost
    
  - name: Get elastic indices stats
    uri:
      url: http://10.233.16.105:9200/_all/_stats
      return_content: yes
    register: indices_stats
    
  - name: Send message when elastic indices
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: Elasticsearch indices "{{ item.indices }}"
    loop: 
      - "{{ indices_stats.json }}"
    delegate_to: localhost
    
  - name: Get elastic nodes stats
    uri:
      url: http://10.233.16.105:9200/_nodes/stats
      return_content: yes
    register: nodes_stats
