- hosts: localhost
  become_user: root
  
  tasks:
  - name: Check web http://{{ smartlis_ip }}/smartlis returns status 200
    uri:
      url: http://{{ smartlis_ip }}/system/about
    register: output
  
  - name: Debug output
    debug:
      var: output
