- hosts: localhost
  
  tasks:
  - name: Get rabbitmq nodes info
    uri:
      url: http://192.1.1.224:15672/api/nodes
      user: guest
      password: guest
      return_content: yes
    register: rabbitmq_health
    
  - name: debug
    debug:
      var: rabbitmq_health.json
