- hosts: "{{ servers }}"
  
  tasks:
  - name: 'Ensure that free space is greater than 20%'
    assert:
      that: 
        - item.size_available > item.size_total|float * 0.2
      msg: "disk space has reached 80% threshold"
    with_items: 
      - "{{ ansible_mounts }}"
    when: ansible_hostname != sldata01
    ignore_errors: yes
    register: disk_space

  - name: Send message when free space is less than 20%
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ ansible_hostname }} {{ item.item.mount }} < 20% free space, {{ ((item.item.size_available / 1024) / 1024) | int }}MB available"
    with_items: 
      - "{{ disk_space.results }}"
    when: item.failed == true
    delegate_to: localhost
