- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: "Check disk space on {{ inventory_hostname }}"
    win_disk_facts:

  - name: "with_subelements and loop example of size check"
    debug:
      var: disk.1.volumes.0.size_remaining
    with_subelements:
      - "{{ ansible_disks }}"
      - partitions
      - flags:
        skip_missing: true
    when:
      - disk.1.drive_letter
    register: volumes
    
  - name: debug
    debug:
      var: volumes.results
