- hosts: "{{ servers }}"
  gather_facts: no
  stdout_callback: yaml
  bin_ansible_callbacks: True

  tasks:
  - name: Check ensemble service status
    win_command: powershell.exe $cpucores = (Get-WMIObject Win32_ComputerSystem).NumberOfLogicalProcessors; (Get-Counter '\Proceso(*)\% de tiempo de procesador').CounterSamples | Select InstanceName, @{Name='CPU %';Expression={[Decimal]::Round(($_.CookedValue / $cpucores), 2)}} | sort *CPU* -Descending | select -First 5 | Format-Table -Autosize
    register: cpu_usage
 
  - name: Output CPU usage facts
    debug:
      var: cpu_usage
      
  - name: Send message when supervisor process is not running
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ cpu_usage.stdout_lines }}"
      parse: full
    delegate_to: localhost

