- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: salida
      
  - name: debug
    debug:
      msg:
        - "PROCESS: {{ item.split()[0] }}"
        - "STATUS: {{ item.split()[1]  }}"
    loop: "{{ salida.stdout_lines }}"
    register: salida2
    
  - name: debug2
    debug:
      var: salida
