- hosts: "{{ servers }}"
  gather_facts: false
  
  tasks:
  - name: Check smartlis web
    ignore_errors: yes
    uri:
      url: http://{{ smartlis_ip }}/system/about
    register: output
    
  - name: debug
    debug:
      var: output

  - name: debug outuput to find error 503
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "Smartlis Backend not working {{ output.url }} --> {{ output.msg }}"
    when: output.failed == true

  - name: fail when url is not working
    fail:
    when: output.failed == true
