- hosts: "{{ servers }}"

  tasks:
  - name: Check ensemble service status
    win_command: powershell.exe (Get-Counter '\Proceso(*)\% de tiempo de procesador').CounterSamples | Select InstanceName, @{Name='CPU %';Expression={[Decimal]::Round(($_.CookedValue / {{ ansible_processor_cores }}), 2)}} | sort *CPU* -Descending | select -First 5 | ConvertTo-Json
    register: cpu_usage

  - name: debug
    debug:
      msg: "{{ cpu_usage.stdout_lines }}"
    loop: cpu_usage
