- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: get volumes
    win_command: powershell.exe "Get-volume | Select-Object "{{ item }}" | ConvertTo-Json"
    with_items:
      - DriveLetter
      - Size
      - SizeRemaining
    register: result
        
  - name: debug
    debug:
      var: result.Size
