- hosts: sldata01
    
  tasks:
  - name: Checking postgresql service is up
    become: yes
    become_method: sudo
    command: service postgresql status
    ignore_errors: yes
    register: postgresql_status
   
  - name: debug outuput to find "inactive" status on stdout
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: postgresql service is not working
      attachments:
        - blocks:
            type: "actions"
            elements:
              type: "button"
              text:
                type: plain_text
                text: "test"
    when: postgresql_status.stdout.find("inactive") != -1
    
  - name: Checking couchdb service is up
    become: yes
    become_method: sudo
    command: service couchdb status
    ignore_errors: yes
    register: couchdb_status
   
  - name: debug outuput to find "inactive" status on stdout
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: couchdb service is not working
    when: couchdb_status.stdout.find("inactive") != -1
