- hosts: "{{ servers }}"
  user: smartlis
    
  tasks:
  - name: Check sys calls count
    command: psql -d sl_log -c "select case when cantidad<100 then 'OK' when cantidad<250 then 'Warning' else 'Danger' end AS Resultado from ( select count(*) Cantidad from public.sys_call_log where ms > 5000 and username not in ('online','AnonymousUser','suser','hcis') and date_part('day',dtcrea)=date_part('day',CURRENT_TIMESTAMP) and date_part('hour', dtcrea)=date_part('hour', CURRENT_TIMESTAMP)-1 ) AS Call_Log"
    ignore_errors: yes
    register: response_time
  
  - name: Send message when user syscalls count is greater than 250 in the last hour
    delegate_to: SE00SANSL
    slack:
      token: T9N25BYMC/BEKR5FXAT/Ed3fUnagKyth6RXeYz9JjElg
      msg: "{{ item }} Número llamadas usuario superior a 5 segundos"
    when: response_time.stdout.find("{{ item }}") != -1
    with_items:
      - "Warning"
      - "Danger"