- hosts: "{{ servers }}"
  user: smartlis
    
  tasks:
  - name: Checking rabbitmq service is up
    become: yes
    become_method: sudo
    command: service rabbitmq-server status
    ignore_errors: yes
    register: rabbitmq_status
   
  - name: debug outuput to find "inactive" status on stdout
    delegate_to: SE00SANSL
    slack:
      token: T9N25BYMC/BEKR5FXAT/Ed3fUnagKyth6RXeYz9JjElg
      msg: rabbitmq service is not working
    when: rabbitmq_status.stdout.find("inactive") != -1
