- hosts: localhost
    
  tasks:
  - name: start PSC session
    uri:
      url: https://192.1.1.139/rest/com/vmware/cis/session
      force_basic_auth: yes
      validate_certs: no
      method: POST
      user: root
      password: "{{ psc_pass }}"
    register: login
    
  - name: debug
    debug:
      var: "{{ login }}"
      
  - name: check PSC health
    uri:
      url: https://192.1.1.139/rest/appliance/health/applmgmt
      force_basic_auth: yes
      validate_certs: no
      headers:
        Cookie: "{{ login.set_cookie }}"
    register: psc_health
      
  - name: debug
    debug:
      msg: "{{ item }}"
    loop: "{{ psc_health }}"
