- hosts: localhost
  
  tasks:
  - name: Get rabbitmq nodes info
    uri:
      url: http://192.1.1.224:15672/api/nodes
      user: guest
      password: guest
      return_content: yes
    register: rabbitmq_health
    
  - name: Send message when rabbitmq alarm=true
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ item.name }}{{ item.mem_alarm }}"
    with_items:
      - "{{ rabbitmq_health.json }}"
    when: item.mem_alarm == false
    delegate_to: localhost
