- hosts: "{{ servers }}"
    
  tasks:
  - name: Check supervisor programs running
    become: yes
    shell: supervisorctl stop all
    
  - name: Backup Backend folder
    archive:
      path: /srv/smartlis/core/backend
      dest: /srv/smartlis/core/backend_backup.tar.gz
      format: gz
      
  - name: Delete not needed files
    become: yes
    command: shopt -s extglob && rm -rf !(sl_root_custom|settings|venv)
    args:
      executable: /bin/bash
      chdir: /srv/smartlis/core/backend/
  
  - name: Deactivate regular expressions
    shell: shopt -u extglob
    args:
      executable: /bin/bash
  
  - name: Extract backend archive
    unarchive:
      src: ftp://10.233.16.3/smartlis/smartlis_backend_4.1.23_build_14560_[20190329T154933].zip
      dest: /srv/smartlis/core/backend
      owner: smartlis
      group: smartlis
      remote_src: yes
      
  - name: Pip install requirements in venv
    pip:
      virtualenv: /srv/smartlis/core/backend/venv
      requirements: /srv/smartlis/core/backend
      extra_args: --upgrade --upgrade-strategy eager -r requirements.txt
      state: present
      
  - name: Execute migrate.py
    script: migrate.py
    args:
      chdir: /srv/smartlis/core/backend
    
  - name: Run supervisor process
    become: yes
    shell: supervisorctl start all
  
  - name: Clear cache
    uri:
      url: localhost:8000/system/clear_cache
    register: clear_cache
    
  - name: debug
    debug:
      var: clear_cache
