- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: get volumes
    win_command: powershell.exe "Get-volume | Select-Object DriveLetter,Size,SizeRemaining | ConvertTo-Json"
    register: Volumes
    
  - name: Set fact
    set_fact:
      size_remaining: "{{ (Volumes.stdout | from_json).Size }}"
        
  - name: debug
    debug:
      var: size_remaining
