- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:
    
  - name: debug
    debug:
      var: ansible_disks[0].partitions[1].number

  - name: debug
    debug:
      var: ansible_disks[0].partitions[1].volumes[0].size
