- hosts: "{{ servers }}"

  tasks:
  - name: Check CPU load average
    win_command: powershell.exe "(Get-Counter '\Proceso(*)\Id. de Proceso').CounterSamples | select Path | ConvertTo-Json"
    register: process_paths
  
  - name: debug
    debug:
      msg: "{{ item }}"
    loop: "{{ process_paths }}"
