---
- hosts: "{{ servers }}"
 
  tasks:
  - name: Get CPU usage
    shell: "top -b -n 1"
    register: top
    
  - name: debug
    debug:
      msg: 
        - "{{ top.stdout_lines[2].split()[1] }}"
        - "{{ top.stdout_lines[2].split()[3] }}"
