- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: "Check disk space on {{ inventory_hostname }}"
    win_disk_facts:

  - name: "with_subelements and loop example of size check"
    assert:
      that: 
        - disk.1.volumes.0.size_remaining > disk.1.volumes.0.size|float * 0.2
      msg: "disk space has reached 80% threshold"
    with_subelements:
      - "{{ ansible_disks }}"
      - partitions
      - flags:
        skip_missing: true
    register: volumes
    
  - name: debug
    debug:
      var: volumes.results[0].disk
