- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: "Check disk space on {{ inventory_hostname }}"
    win_disk_facts:

  - name: "with_subelements and loop example of size check"
    debug:
      var: disk.1.volumes.0.size_remaining
    with_subelements:
      - "{{ ansible_disks }}"
      - partitions
      - flags:
        skip_missing: true
    loop_control:
      loop_var: disk
    # When the drive has a letter, and less than 5 gb remaining
    when:
      - disk.1.drive_letter
  - name: "min"
    debug:
      var: "{{ item.volumes.0.size }}"
    loop: "{{ ansible_disks|subelements('partitions') }}"
