- hosts: "{{ servers }}"
  set_fact:
    supervisor_proc: "{{ superv_status.stdout_lines }}"
    
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: superv_status
    
  - name: debug
    debug:
      msg: "{{ supervisor_proc }}"
