- hosts: localhost

  tasks:
  - name: Provide information about vCenter
    vmware_datastore_facts:
      hostname: '{{ vcenter_host }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      cluster: '{{ cluster }}'
      validate_certs: no
    register: vcenter_about_info
    
  - name: debug info
    debug:
      msg: '{{ item }}'
    loop: '{{ vcenter_about_info.datastores }}'
