- hosts: "{{ servers }}"
    
  tasks:
  - name: check supervisor programs running
    become: yes
    shell: supervisorctl status
    register: supervisor_status
    
  - name: debug
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ supervisor_status.stdout_lines }}"
