- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: "Check disk space on {{ inventory_hostname }}"
    win_disk_facts:

  - name: Test
    win_command: powershell.exe "Get-WmiObject -Class Win32_logicaldisk | Where-Object Drivetype -eq 3 | Select-Object deviceid,size,freespace"
    register: volumes
    
  - name: debug
    debug:
      var: volumes.stdout_lines[0].Size
