- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: get volumes
    win_command: powershell.exe "$DriveLetter= Get-Volume | Select-Object DriveLetter | ConvertTo-Json"
        
  - name: debug
    debug:
      var: DriveLetter
 
  - name: execute powershell
    win_command:  powershell.exe "Get-PSDrive "{{ $DriveLetter }}" | Select-Object Free | ConvertTo-Json"
    register: getpsdrive
    
  - name: debug
    debug:
      var: getpsdrive
