- hosts: "{{ psc_servers }}"

  tasks:
  - name: Checking PSC replica
    become: yes
    shell: /usr/lib/vmware-vmdir/bin/vdcrepadmin -f showpartnerstatus -h localhost -u administrator -w {{ psc_pass }}
    register: replica_status

  - name: debug
    debug:
      msg: "{{ item.split(':')[0] }} {{ item.split(':')[1] }}"
    loop: "{{ replica_status.stdout_lines }}"

