- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: 'Ensure that free space is greater than 20%'
    assert:
      that: 
        - item.size_remaining > item.size|float * 0.2
      msg: "disk space has reached 80% threshold"
    with_items: 
      - "{{ ansible_disks.1.volumes.0 }}"
    ignore_errors: yes
    register: disk_space
