- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl {{ item }}
    with_items:
      - "status"
    register: superv_status
      
  - name: debug
    debug:
      var: superv_status
