- hosts: "{{ servers }}"
  gather_facts: false

  tasks:
  - name: Set service startup mode to auto and ensure it is started
    win_command: powershell.exe "Get-Service -Name W32Time | Select-Object Status | ConvertTo-Json"
    register: service_status
  
  - name: debug
    debug:
      var: service_status
