- hosts: localhost

  tasks:
  - name: Provide information about vCenter
    vmware_datastore_facts:
      hostname: '{{ vcenter_host }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      cluster: '{{ cluster }}'
      validate_certs: no
    register: datastore_info
    
  - name: debug info
    debug:
      msg: '{{ item.freeSpace }}'
    loop: '{{ datastore_info.datastores }}'
    
  - name: 'Ensure that free space is greater than 20%'
    assert:
      that: 
        - item.freeSpace > item.capacity|float * 0.9
      msg: "datastore {{ item.name }} space has reached 80% threshold"
    loop: '{{ datastore_info.datastores }}'
    ignore_errors: yes
    register: datastore_space

  - name: debug info
    debug:
      msg: '{{ item }}'
    loop: 
      - '{{ datastore_space.results }}'

  - name: Send message when free space is less than 20%
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "Datastore {{ item.name }} < 20% free space, {{ ((item.freeSpace / 1024) / 1024) | int }}MB available"
    loop: 
      - "{{ datastore_space.results }}"
    when: item.failed == true
    delegate_to: localhost
