- hosts: "{{ servers }}"
  gather_facts: false

  tasks:
  - name: Set service startup mode to auto and ensure it is started
    win_command: powershell.exe "Get-Service -Name W32Time | Select-Object Status | ConvertTo-Json"
    register: service_status
  
  - name: debug
    debug:
      var: service_status.stdout
  
  - name: debug outuput to find "inactive" status on stdout
    delegate_to: SE00SANSL
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: rabbitmq service is not working
    when: rabbitmq_status.stdout.find("1") != -1
