- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
      
  - name: debug
    debug:
      msg:
        - "PROCESS: {{ item.split()[0] }}"
        - "STATUS: {{ item.split()[1]  }}"
    loop: "{{ salida.stdout_lines }}"
