- hosts: "{{ servers }}"
  gather_facts: false

  tasks:
  - name: Check ensemble service status
    win_command: powershell.exe "Get-Service -Name LanmanServer | Select-Object Status | ConvertTo-Json"
    register: service_status

  - name: debug outuput to find "stopped" or "1" status on stdout
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: LanmanServer service is not working
    when: service_status.stdout.find("4") == -1
    
  - name: Check Tomcat7 service status
    win_command: powershell.exe "Get-Service -Name W32Time | Select-Object Status | ConvertTo-Json"
    register: service_status

  - name: debug outuput to find "stopped" or "1" status on stdout
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: Tomcat7 service is not working
    when: service_status.stdout.find("4") == -1
