- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Check ensemble service status
    win_command: powershell.exe $cpucores = (Get-WMIObject Win32_ComputerSystem).NumberOfLogicalProcessors; (Get-Counter '\Proceso(*)\% de tiempo de procesador').CounterSamples | Select InstanceName, @{Name='CPU %';Expression={[Decimal]::Round(($_.CookedValue / $cpucores), 2)}} | sort *CPU* -Descending | select -First 5
    register: cpu_usage

  - name: Set CPU usage facts
    set_fact:
      system_cpu: "{{ cpu_usage.stdout_lines.split()[2] }}"
 
  - name: Output CPU usage facts
    debug:
      msg:
        - "System CPU usage: {{ system_cpu }}"
