- hosts: "{{ servers }}"
    
  tasks:
  - name: check supervisor programs running
    become: yes
    shell: supervisorctl status
    register: supervisor_status
    
  - name: debug
    debug:
      var: supervisor_status
