- hosts: localhost
    
  tasks:
  - name: Checking PSC replica
    uri:
      url: https://192.1.1.139/rest/appliance/access/shell
      user: root
      password: "{{ psc_pass }}"
      return_content: yes
    register: replica_status
    
  - name: debug
    debug:
      msg: "{{ item }}"
    loop: "{{ replica_status }}"
