- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:
    
  - name: debug
    debug:
      var: ansible_disks.partitions.find("drive_letter") not null

  - name: get volumes
    win_command: powershell.exe "Get-PSDrive | Select-Object -ExpandProperty 'Name' | Select-String -Pattern '^[a-z]$' | ConvertTo-Json"
    register: getvolumes
    
  - name: debug
    debug:
      var: getvolumes.stdout
 
  - name: execute powershell
    win_command:  powershell.exe "Get-PSDrive "{{ getvolumes.stdout_lines }}" | Select-Object Free | ConvertTo-Json"
    register: getpsdrive
    
  - name: debug
    debug:
      var: getpsdrive
