- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: Output first disk space
    debug:
      var: ansible_facts.disks[0].partitions[2].volumes
