- hosts: "{{ psc_servers }}"

  tasks:
  - name: Checking PSC replica
    become: yes
    shell: /usr/lib/vmware-vmdir/bin/vdcrepadmin -f showpartnerstatus -h localhost -u administrator -w {{ psc_pass }}
    register: replica_status

  - name: debug
    debug:
      msg: "{{ item.split()[0] }} {{ item.split()[1] }}"
    loop: "{{ replica_status.stdout_lines }}"
    
  - name: Send message when replica partner changes is not 0
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ ansible_hostname }} {{ item.split()[0] }} is {{ item.split()[2] }}"
    loop: "{{ replica_status.stdout_lines }}"
    when: ("{{ item.split()[0] }}" == 'Partner') and ("{{ item.split()[2] }}" == 0)
    delegate_to: localhost
