- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: superv_status
    
  - set_fact:
      superv_proc: "{{ superv_status.stdout | from_json }}"
    
  - name: debug
    debug:
      var: superv_proc
