- hosts: "{{ servers }}"
    
  tasks:
  - name: check supervisor programs running
    become: yes
    shell: "{{ item }}" status
    with_items:
      - supervisorctl
    register: supervisor_status
    
  - name: debug
    debug:
      var: supervisor_status
