- hosts: "{{ servers }}"

  tasks:
  - name: List process path
    win_command: powershell.exe "(Get-Counter '\Proceso(*)\Id. de Proceso').CounterSamples | select Path | ConvertTo-Json"
    register: process_paths
  
  - name: set process paths fact
    set_fact:
      process_path: "{{ process_paths.stdout | from_json }}"
      
  - name: debug
    debug:
      msg: "{{ item.Path }}"
    loop: "{{ process_path | list }}"

  - name: Check process id from process path
    win_command: powershell.exe "((Get-Counter ('{{ item.Path }}' -replace '\\Id. de proceso','\id. de proceso')).CounterSamples.CookedValue)"
    loop: "{{ process_path | list }}"
    register: process_pid

   - name: debug
    debug:
      msg: "{{ item }}"
    loop: "{{ process_pid | list }}"
