- hosts: "{{ servers }}"
    
  tasks:
  - name: check supervisor programs running
    become: yes
    supervisorctl:
      name: all
      state: present
    register: supervisor_status
    
  - name: debug
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ supervisor_status.stdout }}"
