- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: get volumes
    win_command: powershell.exe "Get-Volume | Select-Object DriveLetter"
    register: getvolumes
    
  - name: debug
    debug:
      var: getvolumes.stdout_lines
 
  - name: execute powershell
    win_command:  powershell.exe "Get-PSDrive "{{ "(getvolumes.stdout | from_json).DriveLetter" }}" | Select-Object Free | ConvertTo-Json"
    register: getpsdrive
    
  - name: debug
    debug:
      var: getpsdrive
