- hosts: "{{ psc_servers }}"

  tasks:
  - name: Checking PSC replica
    become: yes
    shell: /usr/lib/vmware-vmdir/bin/vdcrepadmin -f showpartnerstatus -h localhost -u administrator -w {{ psc_pass }}
    register: replica_status

  - name: Send message when PSC replica partner is not available
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ ansible_hostname }} PSC replica {{ item.split(':')[0] }} is {{ item.split(':')[1]| regex_replace(' ') }}"
    when: ("{{ item.split(':')[0].find("available") }}" != -1) and ("{{ item.split(':')[1] | regex_replace(' ') }}" != 'Yes')
    delegate_to: localhost
    ignore_errors: yes
