- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: salida
      
  - name: debug
    debug:
      msg:
        - "{{ item.split()[0] }}"
        - "{{ item.split()[1] }}"
    loop: "{{ salida.stdout_lines }}"
    
  - name: start previous running supervisor process
    supervisorctl:
      name: "{{ item.split()[0] }}"
      state: started
    loop: "{{ salida.stdout_lines }}"
    when: ("{{ item.split()[1] }}" == 'RUNNING')
