- hosts: "{{ servers }}"
  user: smartlis
    
  tasks:
  - name: Checking elasticsearch service is up
    become: yes
    become_method: sudo
    command: service elasticsearch status
    ignore_errors: yes
    register: elasticsearch_status
   
  - name: debug outuput to find "inactive" status on stdout
    delegate_to: SE00SANSL
    slack:
      token: T9N25BYMC/BEKR5FXAT/Ed3fUnagKyth6RXeYz9JjElg
      msg: elasticsearch service is not working
    when: elasticsearch_status.stdout.find("inactive") != -1
