- hosts: localhost
    
  tasks:
  - name: start VCenter session
    uri:
      url: https://192.1.1.130/rest/com/vmware/cis/session
      force_basic_auth: yes
      validate_certs: no
      method: POST
      user: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
    register: login
    
  - name: debug
    debug:
      var: "{{ login }}"
      
  - name: check VCenter PSC registration
    uri:
      url: https://192.1.1.130/rest/vcenter/system-config/psc-registration
      force_basic_auth: yes
      validate_certs: no
      headers:
        Cookie: "{{ login.set_cookie }}"
    register: psc_health
      
  - name: debug
    debug:
      msg: "{{ item }}"
    loop: 
      - "{{ psc_health }}"
