- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: get volumes
    win_command: powershell.exe "get-psdrive -PSProvider FileSystem | ConvertTo-Json"
    register: getvolumes
    
  - name: debug
    debug:
      var: getvolumes
 
  - name: execute powershell
    win_command:  powershell.exe "Get-PSDrive C | Select-Object Free | ConvertTo-Json"
    register: getpsdrive
    
  - name: debug
    debug:
      var: getpsdrive
