- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: "Check disk space on {{ inventory_hostname }}"
    win_disk_facts:

  - name: "with_subelements and loop example of size check"
    debug:
      var: disk.1.volumes.0.size_remaining
    with_subelements:
      - "{{ ansible_disks }}"
      - partitions
      - flags:
        skip_missing: true
    loop_control:
      loop_var: disk
    when:
      - disk.1.drive_letter
      - disk.1.volumes.0.size_remaining > disk.1.volumes.0.size|float * 0.2
    register: volumes
    
  - name: debug
    debug:
      var: volumes.results[0].disk
