- hosts: "{{ servers }}"
  gather_facts: no

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: Output first disk space
    debug:
      var: ansible_facts.disks[0].partitions[1].volumes
    register: volumes
    
  - name: debug
    debug:
      var: ansible_facts.disks|selectattr("partitions")|first
  
  - name: execute powershell
    win_command:  powershell.exe "Get-PSDrive C | Select-Object Free | ConvertTo-Json"
    register: getpsdrive
    
  - name: debug
    debug:
      var: getpsdrive
