- hosts: "{{ servers }}"
  gather_facts: yes

  tasks:
  - name: "Check disk space on {{ inventory_hostname }}"
    win_disk_facts:

  - name: "with_subelements and loop example of size check"
    assert:
      that: 
        - disk.1.volumes.0.size_remaining > disk.1.volumes.0.size|float * 0.2
      msg: "disk space has reached 80% threshold"
    with_subelements:
      - "{{ ansible_disks }}"
      - partitions
      - flags:
        skip_missing: true
    loop_control:
      loop_var: disk
    ignore_errors: yes
    register: volumes
  
  - name: Debug
    debug:
      var: volumes
      
  - name: Send message when free space is less than 20%
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "{{ ansible_hostname }} unidad {{ item.disk.1.drive_letter }} < 20% free space {{ ((item.disk.1.volumes.0.size_remaining / 1024) / 1024) }}MB available"
    with_items:
      - "{{ volumes.results }}"
    when: item.failed == true
    delegate_to: localhost
