- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: superv_status
    
  - name:
    become: yes
    shell: supervisorctl stop {{ item }}
    with_items:
      - "{{ superv_status.stdout_lines }}"
