- hosts: "{{ servers }}"
    
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: superv_status
    
  - name: debug
    debug:
      ver: superv_status
