- hosts: localhost

  tasks:
  - name: Provide information about vCenter
    vmware_datastore_facts:
      hostname: '{{ vcenter_host }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      cluster: '{{ cluster }}'
      validate_certs: no
    register: datastore_info
    
  - name: debug info
    debug:
      msg: '{{ item.freeSpace }}'
    loop: '{{ datastore.datastores }}'
    
  - name: 'Ensure that free space is greater than 20%'
    assert:
      that: 
        - item.freeSpace > item.capacity|float * 0.2
      msg: "datastore {{ item.name }} space has reached 80% threshold"
    loop: '{{ datastore.datastores }}'
    register: datastore_space

  - name: debug info
    debug:
      msg: '{{ item }}'
    loop: '{{ datastore_space }}'
