- hosts: localhost

  tasks:
  - name: Gather all registered virtual machines
    vmware_vm_facts:
      hostname: 192.1.1.150
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      vm_type: vm
    validate_certs: false
    register: vmfacts

  - debug:
      var: vmfacts.virtual_machines
