- hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Send summy message to SL     
    uri:
      method: POST
      url: "{{ mirth_url }}"
      url_username: "{{ mirth_user }}"
      url_password: "{{ mirth_pass }}"
      headers:
        Content-Type: application/json
      body:
        rawData: "sdsdkjshdjh"
        binary: false
      status_code: 204
      force_basic_auth: yes
      return_content: yes
    ignore_errors: yes
    register: message_status
    
  - name: debug
    debug:
      var: message_status
