- hosts: localhost

  tasks:
  - name: Change Network
    vmware_guest:
      hostname: '{{ vcenter_host }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      folder: /CSI/SL_Aviles_PRE
      datacenter: CSI
      validate_certs: no
      name: "{{ item }}"
      state: poweredoff
      networks:
      - name: SL_Privada
    loop:
      - slapp01
    delegate_to: localhost
