- hosts: "{{ servers }}"
      
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: salida
    
  - name: start previous running supervisor process
    become: yes
    shell: supervisorctl start {{ item.split()[0] }}
    loop: "{{ supervisor_status.stdout_lines }}"
    when: ("{{ item.split()[1] }}" == 'RUNNING')
