- hosts: slapp01
      
  tasks:    
  - name: restart supervisor process
    become: yes
    shell: supervisorctl {{ item }} smartlis-core-backend
    loop:
      - stop
      - start
    loop_control:
      pause: 5
