- hosts: "{{ omnicube }}"
  gather_facts: no
  
  tasks:
  - name: Get auth token
    uri:
      url: https://simplivity@{{ omnicube }}/api/oauth/token
      method: POST
      body: grant_type=password&username={{ vcenter_user }}&password={{ vcenter_pass }}
      return_content: yes
      headers:
        Content-Type: application/x-www-form-urlencoded
      validate_certs: no
    register: token

  - name: Get backups
    uri:
      url: https://{{ omnicube }}/api/backups?virtual_machine_name={{ item }}&omnistack_cluster_name=HUVMSVTCL01&limit=1
      method: GET
      headers:
        Accept: application/vnd.simplivity.v1+json
        Authorization: Bearer {{ token.json.access_token }}
      validate_certs: no
    loop:
      - SE00SANSL
      - SE00SDSL1
    register: backups
    
  - name: Restore Backup
    uri:
      url: https://{{ omnicube }}/api/backups/{{ item.json.backups.0.id }}/restore?restore_original=false
      method: POST
      headers:
        Content-Type: application/vnd.simplivity.v1+json
        Authorization: Bearer {{ token.json.access_token }}
      body: "{\"virtual_machine_name\": \"{{ item.json.backups.0.virtual_machine_name }}_NEW\"}"
      validate_certs: no
      body_format: json
      status_code: 202
    with_items:
      - "{{ backups.results }}"
