- hosts: "{{ servers }}"
    
  tasks:
  - name: Check supervisor status
    become: yes
    shell: supervisorctl status
    register: supervisor_status
  
  - name: Stop all supervisor process
    become: yes
    shell: supervisorctl stop all
    
  - name: Backup Backend folder
    archive:
      path: /srv/smartlis/core/backend
      dest: /srv/smartlis/core/backend_backup_{{ ansible_date_time.date }}.tar.gz
      format: gz
      
  - name: Delete not needed files
    become: yes
    shell: "bash -c 'shopt -s extglob \n rm -rf !(sl_root_custom|settings|venv)'"
    args:
      chdir: /srv/smartlis/core/backend
      
  - name: Disable extglob
    become: yes
    shell: shopt -u extglob
    args:
      executable: /bin/bash
  
  - name: Extract backend archive
    unarchive:
      src: ftp://10.233.16.3/smartlis/smartlis_backend_4.1.27_build_15629_[20190506T162938].zip
      dest: /srv/smartlis/core/backend
      owner: smartlis
      group: smartlis
      remote_src: yes
      
  - name: Pip install requirements in venv
    pip:
      virtualenv: /srv/smartlis/core/backend/venv
      requirements: /srv/smartlis/core/backend/requirements.txt
      extra_args: --upgrade --upgrade-strategy eager
      state: present
      
  - name: Execute migrate.py
    shell: . venv/bin/activate && python migrate.py && deactivate
    args:
      chdir: /srv/smartlis/core/backend
    
  - name: install patch
    patch:
      src: /srv/smartlis/core/backend/patches/0001-interprets_empty_strings_as_nulls.patch
      basedir: /srv/smartlis/core/backend/venv
      strip: 1
      remote_src: yes
    
  - name: start previous running supervisor process
    become: yes
    shell: supervisorctl start {{ item.split()[0] }}
    loop: "{{ supervisor_status.stdout_lines }}"
    when: ("{{ item.split()[1] }}" == 'RUNNING')
  
  - name: Clear cache
    uri:
      url: http://localhost:8000/system/clear_cache/
    register: clear_cache
    
  - name: debug
    debug:
      var: clear_cache
