- hosts: "{{ esx_node }}"
  gather_facts: yes
  
  tasks:
  - name: list vmx files
    find:
      path: /vmfs/volumes/SL_SAN/Test
      patterns: '*.vmx'
      recurse: yes
    register: files
  
  - name: Edit vmx file displayName parameter
    replace:
      path: "{{ item.path }}"
      regexp: 'displayName'
      replace: 's/.$/_BACKUP&/'
    with_items: 
      - "{{ files.files }}"
