- hosts: "{{ esx_node }}"
  gather_facts: no
  
  tasks:
  - name: list vmx files
    find:
      path: /vmfs/volumes/SL_SAN/Test
      patterns: '*.vmx'
      recurse: yes
    register: files
    
  - name: debug
    debug:
      msg: "{{ item.path }}"
    with_items:
      - "{{ files.files }}"
      
  - set_fact:
      "my_{{ item | basename }}": "{{ item }}"
    with_items: "{{ files.files | map(attribute='path') | list }}"
    register: displayname
    
  - name: debug
    debug:
      var: displayname
