- hosts: "{{ esx_node }}"
  gather_facts: no
  
  tasks:
  - name: list vmx files
    find:
      path: /vmfs/volumes/SL_SAN/Test
      patterns: '*.vmx'
      recurse: yes
    register: files
    
  - name: debug
    debug:
      msg: "{{ item.path }}"
    with_items:
      - "{{ files.files }}"
      
  - name: Register displayname
    lineinfile:
      path: "{{ item.path }}"
      regexp: '^displayName'
    with_items:
      - "{{ files.files }}"
    register: displayname
