- hosts: "{{ esx_node }}"
  gather_facts: yes
  
  tasks:
  - name: list vmx files
    find:
      path: /vmfs/volumes/SL_SAN/Test
      patterns: '*.vmx'
      recurse: yes
    register: files
  
  - name: Edit vmx file displayName parameter
    lineinfile:
      path: "{{ item.path }}"
      regexp: 's/.$/_BACKUP&/'
      line: 'displayName'
    with_items: 
      - "{{ files.files }}"
  
  - name: Register Backups
    shell: vim-cmd solo/registervm {{ item.path }}
    with_items: 
      - "{{ files.files }}"
