- hosts: "{{ esx_node }}"
  gather_facts: no
  
  tasks:
  - name: list vmx files
    find:
      path: /vmfs/volumes/SL_SAN/
      patterns: '*.vmx'
      recurse: yes
    register: files
    
  - name: debug
    debug:
      msg: "{{ item.files[0].path }}"
    with_items: "{{ files.stdout }}"
