- hosts: "{{ esx_node }}"
  gather_facts: no
  
  tasks:
  - name: list vmx files
    find:
      path: /vmfs/volumes/SL_SAN/
      patterns: '*.vmx'
      recurse: yes
    register: files
    
  - name: debug
    debug:
      msg: "{{ item.path }}"
    with_items:
      - "{{ files.files }}"
      
  - name: list vmx files
    find:
      path: /vmfs/volumes/SL_SAN/
      file_type: directory
      recurse: yes
    register: directories
    
  - name: debug
    debug:
      msg: "{{ item.path }}"
    with_items:
      - "{{ directories.files }}"
